/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.lj.mytest.demo.service.api.avro;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface AvroHelloService {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"AvroHelloService\",\"namespace\":\"com.lj.mytest.demo.service.api.avro\",\"types\":[],\"messages\":{\"ping\":{\"request\":[],\"response\":\"string\"}}}");
  /**
   */
  java.lang.CharSequence ping() throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends AvroHelloService {
    public static final org.apache.avro.Protocol PROTOCOL = com.lj.mytest.demo.service.api.avro.AvroHelloService.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void ping(org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
  }
}