// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.lj.mytest.demo.service.api.grpc;

public interface PingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hello.PingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
