// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.lj.mytest.demo.service.api.grpc;

public interface PingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hello.PingRequest)
    com.google.protobuf.MessageOrBuilder {
}
